### PR TITLE
fixes for updated dart analysis and pana

### LINKED ISSUE #262: Improve static analysis (pana + new lints)
### Motivation

This issue tracks 2 main parts to update with the base ROHD repo (https://github.com/intel/rohd/)
- Leverage new linting (update analysis options)
- Enable pana to check for pub.dev score

### Desired solution

Reference how the base ROHD repo is doing it (e.g. https://github.com/intel/rohd/pull/621)

### Alternatives considered

_No response_

### Additional details

_No response_

### PR DESCRIPTION
**Pull request by desmonddak**
## Description & Motivation

Update dart analysis settings and add pano analysis for pub.dev score generation.

## Related Issue(s)

Fix #262

## Testing

Ran dart test.

## Backwards-compatibility

> Is this a breaking change that will not be backwards-compatible? If yes, how so?

No

## Documentation

> Does the change require any updates to documentation? If so, where? Are they included?

No change needed.

### CODE REVIEW

File: lib/src/arithmetic/values/fixed_point_value.dart [hunk 1]
```diff
@@ -16,7 +16,7 @@ export 'fixed_point_populator.dart';
 
 /// An immutable representation of (un)signed fixed-point values following
 /// Q notation (Qm.n format) as introduced by
-/// (Texas Instruments)[https://www.ti.com/lit/ug/spru565b/spru565b.pdf].
+/// (Texas Instruments: (https://www.ti.com/lit/ug/spru565b/spru565b.pdf).
```
Comment (mkorbel1) [inline lib/src/arithmetic/values/fixed_point_value.dart]: typo: this file and `fixed_point_logic.dart` have resolved this same lint issue in two different ways, one is missing a space and this one has unmatched parentheses

File: analysis_options.yaml [hunk 2]
```diff
@@ -7,7 +7,8 @@ analyzer:
     strict-inference: true
     strict-raw-types: true
   exclude:
-    - confapp/**
```
Comment (mkorbel1) [inline analysis_options.yaml:10]: i think this was a mis-copy-paste to change these couple lines?

**Review by mkorbel1 — COMMENTED** [review]
Thank you for doing this again on another repo!

File: analysis_options.yaml (hunk 2 above)
Comment (desmonddak) [reply analysis_options.yaml:10]: Yup.  Learned this the hard way.

File: analysis_options.yaml [hunk 3]
```diff
@@ -7,6 +7,7 @@ analyzer:
     strict-inference: true
     strict-raw-types: true
   exclude:
+    - confapp/**
     - doc/tutorials/chapter_9/rohd_vf_example
```
Comment (mkorbel1) [inline analysis_options.yaml]: also these two paths don't exist in rohd-hcl i think

**Review by mkorbel1 — APPROVED** [review]
Looks great, thank you!
